### PR TITLE
Fix blog post typo

### PR DESCRIPTION
**Pull request by stevennyman**

### CODE REVIEW

**Comment by ihucos** [comment]
<3

**Comment by ihucos** [comment]
Thanks! ❤️

**Comment by ihucos** [comment]
Interesting that I am testing pageviews and did not see anybody accessing that blog post, do you have any tracking blockers or javascript disabled or sth like this by any chance 😃

**Comment by stevennyman** [comment]
I use uBlock Origin which tends to block the tracking. Also I happen to prefer the inline script but I understand that a remote-hosted script is easier to update. :)

**Comment by ihucos** [comment]
> I use uBlock Origin which tends to block the tracking.

gitcha

> Also I happen to prefer the inline script but I understand that a remote-hosted script is easier to update. :)

Yeah, I also prefer the inline script but it was getting too big now that we started tracking pageviews. I imagine for most people it's more convenient to only copy paste one line of code and I believe most users don't care about the glory details but who knows, maybe I am wrong.

**Comment by stevennyman** [comment]
You could offer an option to pick between inline script and remote hosted. Copying and pasting one line of code vs several lines of code does take about the same level of effort. While I think remote-hosted is a sensible default, I do like having inline as an option (the inline script was actually one of the reasons I decided to try counter.dev in the first place).

**Comment by ihucos** [comment]
Yeah, lets let the externally hosted script mature now with the pageviews feature. Before it it not change for two years or something like this. But now there definitely will be some changes there to facilitate new metrics.

**Pull request merged**
